# Generated by Django 2.2.4 on 2019-08-29 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('numero_de_lote', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_espuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=100)),
                ('especial', models.BooleanField()),
                ('linea', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_de_unidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('modelo', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=200)),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Figura')),
            ],
        ),
        migrations.CreateModel(
            name='Block_de_espuma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('numero_de_block', models.IntegerField(verbose_name='numero de block')),
                ('desperdicio', models.BooleanField()),
                ('curado', models.BooleanField()),
                ('largo', models.DecimalField(decimal_places=4, max_digits=8)),
                ('largo_curado', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ancho', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ancho_curado', models.DecimalField(decimal_places=4, max_digits=8)),
                ('alto', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('alto_curado', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('flujo_de_aire', models.DecimalField(decimal_places=4, max_digits=8)),
                ('peso', models.DecimalField(decimal_places=4, max_digits=8)),
                ('defecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Defecto')),
                ('figura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Figura')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Lote')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Maquina')),
                ('tipo_de_espuma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Tipo_de_espuma')),
                ('tipo_de_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invapp.Tipo_de_unidad')),
            ],
        ),
    ]
