# Generated by Django 2.2.4 on 2019-08-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_de_espuma',
            name='alto',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='block_de_espuma',
            name='alto_curado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='block_de_espuma',
            name='ancho_curado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='block_de_espuma',
            name='defecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invapp.Defecto'),
        ),
        migrations.AlterField(
            model_name='block_de_espuma',
            name='largo_curado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
